### ISSUE TITLE
setState(...): Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by renaudl** [matthewwithanm/react-inlinesvg#35] opened 2016-07-26 09:31 UTC
Hi

The IsSVG component added to my app make react crying on the following. Could you please help.

setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.

**Comment by renaudl** [comment] 2016-07-26 09:52
Comes from the setState in the handleLoad callback. Not sure why it generates this warning. Any idea?

**Comment by pozylon** [comment] 2016-09-07 09:27
`fail(error) {
    const status = error.isUnsupportedBrowserError ? Status.UNSUPPORTED : Status.FAILED;

    this.setState({ status }, () => {
      if (typeof this.props.onError === 'function') {
        this.props.onError(error);
      }
    });
  }

  handleLoad(err, res) {
    if (err) {
      this.fail(err);
      return;
    }
    this.setState({
      loadedText: res.text,
      status: Status.LOADED
    }, () => (typeof this.props.onLoad === 'function' ? this.props.onLoad() : null));
  }`

this.isMounted missing

**Comment by gilbarbara** [comment] 2016-10-08 01:03
@renaudl 
It's hard to know why it is complaining about `setState` in your setup. Can you reproduce it using jsfiddle or similar?

@pozylon https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html

**Comment by nikoloza** [comment] 2016-12-29 04:41
Same here: it shows that error when you toggle remove and add it or parent element. Will try to reproduce it in fiddle.

**Comment by pozylon** [comment] 2016-12-29 07:51
@gilbarbara thanks for posting that link about isMounted, i might have some memory leaks in my app then...

Btw:
The setState warning suddenly disappeared in my project, I have the strong feeling that it had something to do with the componentWillMount -> componentDidMount change. Since Sep 7 I updated react-inlinesvg, react, react-dom and a lot of other packages so it's hard to tell.

**Comment by gilbarbara** [comment] 2016-12-29 13:41
I'm having this error in an app I'm working on. I'll try to understand what's going on and let you know.

**Comment by gilbarbara** [comment] 2017-01-04 03:11
Fixed in 4103c1b268f2771ccaae8d4e43d628ec1ff0891f

**Closed by gilbarbara** 2017-01-04 03:11 UTC
