### ISSUE TITLE
Extra characters ]> added to the span tag

### ISSUE THREAD

**Issue by ameego** [matthewwithanm/react-inlinesvg#13] opened 2015-06-24 11:16 UTC
Hi, 

I'm getting a couple of extra characters "]>" added to the span tag.

Here's the code:

```javascript
var Isvg = require('react-inlinesvg');
<Isvg src="./img/icons/my-icon.svg"></Isvg>
```

The output is as follow:

```html
<span class="isvg loaded" data-reactid=".0.1.2.0">
   <!--?xml version="1.0" encoding="utf-8"?-->
   <!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
   ]>
   <svg>
      ...
   </svg>
</span>
```

Do you have any idea why this extra characters appears?

Cheers!

**Comment by matthewwithanm** [comment] 2015-06-25 00:32
That's really weird. Can you create a test case where I can reproduce the issue?

**Comment by ameego** [comment] 2015-06-25 02:45
Hi there,

I've changed my export settings in Illustrator and it does work fine now.
Let me know if you still need information.

Cheers,

**Comment by matthewwithanm** [comment] 2015-06-25 14:32
Any chance I can get the original file?

**Comment by ameego** [comment] 2015-06-26 08:08
Sure, here you go: https://drive.google.com/file/d/0B4i5pei2tx48bTJGMEJoeWlUUGs/view?usp=sharing.

I've just tried it and I can reproduce the issue with it.

**Comment by tnrich** [comment] 2016-01-14 00:34
I'm running into this issue as well

**Comment by scriptin** [comment] 2016-03-11 21:56
These characters are closing tag for `DOCTYPE`. Here is an example file I use: [04eba.svg](https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/04eba.svg). When I remove `DOCTYPE` from this file, these two characters do not appear.

When I inspect the DOM, I see this:

    <span class="isvg loaded" data-reactid=".0.1.0.1.1.$0">
    
    
    
    ]>
    <svg xmlns="http://www.w3.org/2000/svg" width="109" height="109" viewBox="0 0 109 109">

So, `<?xml>` turns into a comment, comments are left as-is, but `DOCTYPE` turns into a mess: one part of it is removed, other part turns into a comment, and the last bit is interpreted as text node.

**Comment by scriptin** [comment] 2016-03-11 22:20
This is actually an issue of React: facebook/react/issues/1035 - in short, React does not support doctypes and things like conditional comments by design.

The best solution in this case is to strip doctype from a loaded document, or maybe even stripping everything before opening `<svg>` tag.

**Comment by gilbarbara** [comment] 2016-04-19 21:34
spring cleaning

**Closed by gilbarbara** 2016-04-19 21:34 UTC
